apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-static-01
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
  hostPath:
    path: /tmp/k8s-pv-static
    type: DirectoryOrCreate
