apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-static-01
  namespace: nginx-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: manual-hostpath
