apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
  namespace: nginx-ns
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
