apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: nginx-ns
  labels:
    app: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs        # RS adopts any pod with this label
  template:
    metadata:
      labels:
        app: nginx-rs      # must match selector.matchLabels
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
