apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-static-01
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-postgres
  hostPath:
    path: /tmp/k8s-pgdata-static
    type: DirectoryOrCreate
