apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-static-01
  namespace: nginx-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-postgres
