apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pvc
  namespace: nginx-ns
  labels:
    app: postgres-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pvc
  template:
    metadata:
      labels:
        app: postgres-pvc
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-auth
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc-postgres-static-01
